// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5GwT9I--y7jkZYsnpCx3c_e5psP3EkIw',
    appId: '1:32312924654:web:28a80caed3fb89a51856ff',
    messagingSenderId: '32312924654',
    projectId: 'social-media-app-329ef',
    authDomain: 'social-media-app-329ef.firebaseapp.com',
    storageBucket: 'social-media-app-329ef.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ7otvcLLb8KGMdR18uE0mq4CQdx8T8-A',
    appId: '1:32312924654:android:d21b2e104bd8f0c61856ff',
    messagingSenderId: '32312924654',
    projectId: 'social-media-app-329ef',
    storageBucket: 'social-media-app-329ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY4WRIU-scAcX6QleC0FXGZvirB3vIR-Y',
    appId: '1:32312924654:ios:7ff1af2b767c7d771856ff',
    messagingSenderId: '32312924654',
    projectId: 'social-media-app-329ef',
    storageBucket: 'social-media-app-329ef.appspot.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY4WRIU-scAcX6QleC0FXGZvirB3vIR-Y',
    appId: '1:32312924654:ios:190efc374c38749b1856ff',
    messagingSenderId: '32312924654',
    projectId: 'social-media-app-329ef',
    storageBucket: 'social-media-app-329ef.appspot.com',
    iosBundleId: 'com.example.socialMediaApp.RunnerTests',
  );
}
